# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: []
-   repo: https://github.com/python-poetry/poetry
    rev: '1.5.1'
    hooks:
    -   id: poetry-check
-   repo: local
    hooks:
    -   id: blue
        name: blue
        entry: blue
        language: system
        types: [python]
    -   id: ruff
        name: ruff
        entry: ruff check --fix --exit-non-zero-on-fix
        language: system
        types: [python]
